inhibit_all_warnings!

# version = '3.0.0'
version = '~> 3.0'

target 'iOS Example' do
  platform :ios, '9.0'
end

target 'BLBackgroundRealm_iOS' do
  platform :ios, '9.0'
  
  pod 'Realm', version
  
  target 'iOS Tests' do
      inherit! :search_paths
      
      pod 'Realm/Headers', version
  end
end

target 'BLBackgroundRealm_watchOS' do
    platform :watchos, '3.0'
    
    pod 'Realm', version
end

target 'tvOS Example' do
    platform :tvos, '10.0'
end

target 'BLBackgroundRealm_tvOS' do
    platform :tvos, '10.0'
    
    pod 'Realm', version
    
    target 'tvOS Tests' do
        inherit! :search_paths

        pod 'Realm/Headers', version
    end
end

target 'macOS Example' do
    platform :osx, '10.10'
end

target 'BLBackgroundRealm_macOS' do
    platform :osx, '10.10'
    
    pod 'Realm', version
    
    target 'macOS Tests' do
        inherit! :search_paths

        pod 'Realm/Headers', version
    end
end
